version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    open-pull-requests-limit: 100
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
