version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    open-pull-requests-limit: 100
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "net.minecraftforge.gradle:ForgeGradle"
        update-types: ["version-update:semver-major"]
      - dependency-name: "com.github.johnrengelman.shadow"
        update-types: ["version-update:semver-major"]
