name: Feature Request [EN]
description: Create a request to add some feature
labels: [enhancement, not-checked]
assignees:
  - anatawa12
body:

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a feature.

  - type: checkboxes
    id: terms
    attributes:
      label: Feature report check list
      options:
        - label: What you want is not included in the latest snapshot version of fixRTM.
          required: true
        - label: You couldn't find same request in the issues.
          required: true

  - type: textarea
    attributes:
      label: Describe the feature
      description: A clear and concise description of what you want.
    validations:
      required: true
