name: 新機能のリクエスト [JA]
description: 追加機能のリクエスト
labels: [enhancement, not-checked]
assignees:
  - anatawa12
body:

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a feature.

  - type: checkboxes
    id: terms
    attributes:
      label: Feature report check list
      options:
        - label: 最新のSNAPSHOTバージョンの fixRTM にその機能が存在しないこと
          required: true
        - label: issues でそのリクエストがまだ無いこと。
          required: true

  - type: textarea
    attributes:
      label: Describe the feature
      description: なにを追加してほしいかを説明してください。
    validations:
      required: true
